"""initial schema

Revision ID: 71f4c36396e8
Revises: 
Create Date: 2026-09-11 19:17:32.376754
"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '71f4c36396e8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('news_articles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url_hash', sa.String(length=64), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('source_domain', sa.String(length=255), nullable=True),
    sa.Column('author', sa.String(length=255), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('raw', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url_hash')
    )
    op.create_index(op.f('ix_news_articles_source_domain'), 'news_articles', ['source_domain'], unique=False)
    op.create_index('ix_news_published_at', 'news_articles', ['published_at'], unique=False)
    op.create_table('news_query_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cache_key', sa.String(length=64), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('query', sa.Text(), nullable=False),
    sa.Column('params', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('response', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cache_key')
    )
    op.create_index(op.f('ix_news_query_cache_expires_at'), 'news_query_cache', ['expires_at'], unique=False)
    op.create_table('tickers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=16), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=True),
    sa.Column('sector', sa.String(length=128), nullable=True),
    sa.Column('industry', sa.String(length=128), nullable=True),
    sa.Column('exchange', sa.String(length=32), nullable=True),
    sa.Column('currency', sa.String(length=8), nullable=True),
    sa.Column('peers', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('peers_resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ingest_status', sa.Enum('pending', 'running', 'complete', 'failed', name='ingest_status', native_enum=False, length=16), nullable=False),
    sa.Column('ingest_error', sa.Text(), nullable=True),
    sa.Column('last_ingested_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ingest_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tickers_symbol'), 'tickers', ['symbol'], unique=True)
    op.create_table('conversations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('ticker_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ticker_id'], ['tickers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('movements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('daily_return', sa.Float(), nullable=False),
    sa.Column('abs_return', sa.Float(), nullable=False),
    sa.Column('direction', sa.Enum('up', 'down', name='direction', native_enum=False, length=16), nullable=False),
    sa.Column('prev_adj_close', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('adj_close', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('volume', sa.BigInteger(), nullable=True),
    sa.Column('rolling_std', sa.Float(), nullable=True),
    sa.Column('threshold', sa.Float(), nullable=False),
    sa.Column('threshold_source', sa.String(length=16), nullable=False),
    sa.Column('detector_k', sa.Float(), nullable=False),
    sa.Column('detector_window', sa.Integer(), nullable=False),
    sa.Column('detector_floor', sa.Float(), nullable=False),
    sa.Column('news_status', sa.Enum('pending', 'complete', 'failed', name='news_status', native_enum=False, length=16), nullable=False),
    sa.Column('news_fetched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ticker_id'], ['tickers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticker_id', 'date', name='uq_movement_ticker_date')
    )
    op.create_index('ix_movement_ticker_date', 'movements', ['ticker_id', 'date'], unique=False)
    op.create_index(op.f('ix_movements_abs_return'), 'movements', ['abs_return'], unique=False)
    op.create_index(op.f('ix_movements_direction'), 'movements', ['direction'], unique=False)
    op.create_table('price_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('open', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('high', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('low', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('close', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('adj_close', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('volume', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['ticker_id'], ['tickers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticker_id', 'date', name='uq_price_ticker_date')
    )
    op.create_index('ix_price_ticker_date', 'price_history', ['ticker_id', 'date'], unique=False)
    op.create_table('chat_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.Enum('user', 'assistant', name='message_role', native_enum=False, length=16), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('sources', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_chat_conversation', 'chat_messages', ['conversation_id', 'id'], unique=False)
    op.create_table('movement_news_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('movement_id', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('relevance_tier', sa.Enum('easy', 'medium', 'hard', name='relevance_tier', native_enum=False, length=16), nullable=False),
    sa.Column('relevance_score', sa.Float(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('search_tier', sa.String(length=16), nullable=True),
    sa.Column('scored_by', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['news_articles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['movement_id'], ['movements.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('movement_id', 'article_id', name='uq_link_movement_article')
    )
    op.create_index('ix_link_movement_tier', 'movement_news_links', ['movement_id', 'relevance_tier'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_link_movement_tier', table_name='movement_news_links')
    op.drop_table('movement_news_links')
    op.drop_index('ix_chat_conversation', table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_index('ix_price_ticker_date', table_name='price_history')
    op.drop_table('price_history')
    op.drop_index(op.f('ix_movements_direction'), table_name='movements')
    op.drop_index(op.f('ix_movements_abs_return'), table_name='movements')
    op.drop_index('ix_movement_ticker_date', table_name='movements')
    op.drop_table('movements')
    op.drop_table('conversations')
    op.drop_index(op.f('ix_tickers_symbol'), table_name='tickers')
    op.drop_table('tickers')
    op.drop_index(op.f('ix_news_query_cache_expires_at'), table_name='news_query_cache')
    op.drop_table('news_query_cache')
    op.drop_index('ix_news_published_at', table_name='news_articles')
    op.drop_index(op.f('ix_news_articles_source_domain'), table_name='news_articles')
    op.drop_table('news_articles')
    # ### end Alembic commands ###
